// <auto-generated />
using System;
using Barbearia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MinhaApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518213423_CriarTabelaServicos")]
    partial class CriarTabelaServicos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Barbearia.Models.Agendamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BarbeiroNome")
                        .HasColumnType("longtext");

                    b.Property<string>("Corte")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataDia");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time(6)");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("PaymentId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("statuspagamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("agendamento");
                });

            modelBuilder.Entity("Barbearia.Models.Servico", b =>
                {
                    b.Property<int>("IdCorte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCorte"));

                    b.Property<string>("NomeCorte")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("IdCorte");

                    b.ToTable("Servicos");

                    b.HasData(
                        new
                        {
                            IdCorte = 1,
                            NomeCorte = "Corte Degradê",
                            Preco = 30.00m,
                            Tipo = 0
                        },
                        new
                        {
                            IdCorte = 2,
                            NomeCorte = "Barba",
                            Preco = 15.00m,
                            Tipo = 1
                        },
                        new
                        {
                            IdCorte = 3,
                            NomeCorte = "Sobrancelha",
                            Preco = 5.00m,
                            Tipo = 2
                        },
                        new
                        {
                            IdCorte = 4,
                            NomeCorte = "Corte Social",
                            Preco = 25.00m,
                            Tipo = 3
                        },
                        new
                        {
                            IdCorte = 5,
                            NomeCorte = "Pézinho",
                            Preco = 10.00m,
                            Tipo = 4
                        },
                        new
                        {
                            IdCorte = 6,
                            NomeCorte = "Cavanhaque",
                            Preco = 10.00m,
                            Tipo = 7
                        },
                        new
                        {
                            IdCorte = 7,
                            NomeCorte = "Alisamento",
                            Preco = 25.00m,
                            Tipo = 20
                        },
                        new
                        {
                            IdCorte = 8,
                            NomeCorte = "Corte só na Tesoura",
                            Preco = 30.00m,
                            Tipo = 6
                        },
                        new
                        {
                            IdCorte = 9,
                            NomeCorte = "Corte só na Máquina",
                            Preco = 15.00m,
                            Tipo = 5
                        },
                        new
                        {
                            IdCorte = 10,
                            NomeCorte = "Corte e Cavanhaque",
                            Preco = 40.00m,
                            Tipo = 18
                        },
                        new
                        {
                            IdCorte = 11,
                            NomeCorte = "Corte e Platinado",
                            Preco = 100.00m,
                            Tipo = 14
                        },
                        new
                        {
                            IdCorte = 12,
                            NomeCorte = "Social e Barba",
                            Preco = 40.00m,
                            Tipo = 10
                        },
                        new
                        {
                            IdCorte = 13,
                            NomeCorte = "Degradê e Alisamento",
                            Preco = 55.00m,
                            Tipo = 16
                        },
                        new
                        {
                            IdCorte = 14,
                            NomeCorte = "Degradê, Alisamento e Barba",
                            Preco = 70.00m,
                            Tipo = 17
                        },
                        new
                        {
                            IdCorte = 15,
                            NomeCorte = "Degradê e Luzes",
                            Preco = 90.00m,
                            Tipo = 12
                        },
                        new
                        {
                            IdCorte = 16,
                            NomeCorte = "Degradê e Reflexo",
                            Preco = 95.00m,
                            Tipo = 13
                        },
                        new
                        {
                            IdCorte = 17,
                            NomeCorte = "Degradê, Pigmentação e Cavanhaque",
                            Preco = 65.00m,
                            Tipo = 19
                        },
                        new
                        {
                            IdCorte = 18,
                            NomeCorte = "Degradê,Risquinho e Pigmentação",
                            Preco = 65.00m,
                            Tipo = 15
                        },
                        new
                        {
                            IdCorte = 19,
                            NomeCorte = "Raspar na Gilette",
                            Preco = 20.00m,
                            Tipo = 8
                        },
                        new
                        {
                            IdCorte = 20,
                            NomeCorte = "Pigmentação",
                            Preco = 25.00m,
                            Tipo = 9
                        },
                        new
                        {
                            IdCorte = 21,
                            NomeCorte = "Degradê e Barba",
                            Preco = 45.00m,
                            Tipo = 11
                        });
                });

            modelBuilder.Entity("Barbearia.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Perfil")
                        .HasColumnType("longtext");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
