// <auto-generated />
using System;
using Barbearia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MinhaApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526213456_CorrigindoIdUsuario")]
    partial class CorrigindoIdUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Barbearia.Models.Agendamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BarbeiroNome")
                        .HasColumnType("longtext");

                    b.Property<string>("Corte")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataDia");

                    b.Property<string>("EmailCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time(6)");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("longtext");

                    b.Property<long?>("PaymentId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("statuspagamento")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("agendamento");
                });

            modelBuilder.Entity("Barbearia.Models.Servico", b =>
                {
                    b.Property<int>("IdCorte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCorte"));

                    b.Property<string>("NomeCorte")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdCorte");

                    b.ToTable("Servicos");

                    b.HasData(
                        new
                        {
                            IdCorte = 1,
                            NomeCorte = "Corte Degradê",
                            Preco = 30.00m,
                            Tipo = "Degrade"
                        },
                        new
                        {
                            IdCorte = 2,
                            NomeCorte = "Barba",
                            Preco = 15.00m,
                            Tipo = "Barba"
                        },
                        new
                        {
                            IdCorte = 3,
                            NomeCorte = "Sobrancelha",
                            Preco = 5.00m,
                            Tipo = "Sobrancelha"
                        },
                        new
                        {
                            IdCorte = 4,
                            NomeCorte = "Corte Social",
                            Preco = 25.00m,
                            Tipo = "Social"
                        },
                        new
                        {
                            IdCorte = 5,
                            NomeCorte = "Pézinho",
                            Preco = 10.00m,
                            Tipo = "Pézinho"
                        },
                        new
                        {
                            IdCorte = 6,
                            NomeCorte = "Cavanhaque",
                            Preco = 10.00m,
                            Tipo = "Cavanhaque"
                        },
                        new
                        {
                            IdCorte = 7,
                            NomeCorte = "Alisamento",
                            Preco = 25.00m,
                            Tipo = "Alisamento"
                        },
                        new
                        {
                            IdCorte = 8,
                            NomeCorte = "Corte só na Tesoura",
                            Preco = 30.00m,
                            Tipo = "CorteTesoura"
                        },
                        new
                        {
                            IdCorte = 9,
                            NomeCorte = "Corte só na Máquina",
                            Preco = 15.00m,
                            Tipo = "CorteMáquina"
                        },
                        new
                        {
                            IdCorte = 10,
                            NomeCorte = "Corte e Cavanhaque",
                            Preco = 40.00m,
                            Tipo = "CorteCavanhaque"
                        },
                        new
                        {
                            IdCorte = 11,
                            NomeCorte = "Corte e Platinado",
                            Preco = 100.00m,
                            Tipo = "CortePlatinado"
                        },
                        new
                        {
                            IdCorte = 12,
                            NomeCorte = "Social e Barba",
                            Preco = 40.00m,
                            Tipo = "SocialBarba"
                        },
                        new
                        {
                            IdCorte = 13,
                            NomeCorte = "Degradê e Alisamento",
                            Preco = 55.00m,
                            Tipo = "DegradeAlisamento"
                        },
                        new
                        {
                            IdCorte = 14,
                            NomeCorte = "Degradê, Alisamento e Barba",
                            Preco = 70.00m,
                            Tipo = "DegradeAlisamentoBarba"
                        },
                        new
                        {
                            IdCorte = 15,
                            NomeCorte = "Degradê e Luzes",
                            Preco = 90.00m,
                            Tipo = "DegradeLuzes"
                        },
                        new
                        {
                            IdCorte = 16,
                            NomeCorte = "Degradê e Reflexo",
                            Preco = 95.00m,
                            Tipo = "DegradeReflexo"
                        },
                        new
                        {
                            IdCorte = 17,
                            NomeCorte = "Degradê, Pigmentação e Cavanhaque",
                            Preco = 65.00m,
                            Tipo = "DegradePigmentaçaoCavanhaque"
                        },
                        new
                        {
                            IdCorte = 18,
                            NomeCorte = "Degradê,Risquinho e Pigmentação",
                            Preco = 65.00m,
                            Tipo = "DegradeRisquinhoPigmentaçao"
                        },
                        new
                        {
                            IdCorte = 19,
                            NomeCorte = "Raspar na Gilette",
                            Preco = 20.00m,
                            Tipo = "RasparGilette"
                        },
                        new
                        {
                            IdCorte = 20,
                            NomeCorte = "Pigmentação",
                            Preco = 25.00m,
                            Tipo = "Pigmentação"
                        },
                        new
                        {
                            IdCorte = 21,
                            NomeCorte = "Degradê e Barba",
                            Preco = 45.00m,
                            Tipo = "DegradeBarba"
                        });
                });

            modelBuilder.Entity("Barbearia.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Perfil")
                        .HasColumnType("longtext");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
